"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['installer.py']


DATA_FILES = {'render.html', 'm.uf2', 'pyboard.py', 'picnic.css', 'style.css', 'config.json'}
OPTIONS = {'iconfile': 'icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)



